# Generated by Django 2.0.2 on 2018-02-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=(), related_name='comments', to='blog.Post'),
        ),
    ]
